// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31eKL5O-f4wFblIBpjKbjKfIG76W8C_Q',
    appId: '1:623164379206:android:135e35a6414b65ebedfa47',
    messagingSenderId: '623164379206',
    projectId: 'hnmarket',
    storageBucket: 'hnmarket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqJFK978z3bsdOSZppqGDLv3t7ry8fQs',
    appId: '1:623164379206:ios:ef89e62a3d632e6bedfa47',
    messagingSenderId: '623164379206',
    projectId: 'hnmarket',
    storageBucket: 'hnmarket.appspot.com',
    androidClientId:
        '623164379206-85dt82rujrsu3lgdu5a91kecqo4l0f7l.apps.googleusercontent.com',
    iosClientId:
        '623164379206-jr7dfqkuua1ueppeochom5rskgs5dkrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicStore',
  );
}
