// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/audit_log.dart';
import 'data/models/customer.dart';
import 'data/models/goods_receipt.dart';
import 'data/models/order.dart';
import 'data/models/payment.dart';
import 'data/models/product.dart';
import 'data/models/product_bundle.dart';
import 'data/models/product_price.dart';
import 'data/models/product_variant.dart';
import 'data/models/promotion.dart';
import 'data/models/purchase_order.dart';
import 'data/models/return.dart';
import 'data/models/stock_adjustment.dart';
import 'data/models/stock_transfer.dart';
import 'data/models/store.dart';
import 'data/models/supplier.dart';
import 'data/models/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7653769325578297450),
    name: 'AppUser',
    lastPropertyId: const obx_int.IdUid(6, 6956002095722061760),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4836424269859791078),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5148251519719062009),
        name: 'username',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 5680444027649533013),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3468178682423991955),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1354394013510638668),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6956002095722061760),
        name: 'roleValue',
        type: 2,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4690907995870872486),
    name: 'AuditLog',
    lastPropertyId: const obx_int.IdUid(5, 5857079913890371898),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1976171610891177639),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3352537870370302081),
        name: 'userId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 6935980218329734149),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1336347101867317298),
        name: 'action',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 505633217611735346),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6895981658410684635),
        name: 'details',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5857079913890371898),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7789117475400079282),
    name: 'GoodsReceipt',
    lastPropertyId: const obx_int.IdUid(6, 6065869732790183717),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6705623597704312502),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2791063891418725910),
        name: 'supplierId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(4, 4748597201642852655),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4751354367855716736),
        name: 'purchaseOrderId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 6296014051876828788),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5351238087487419695),
        name: 'receivedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2054030888950854220),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6065869732790183717),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2878934790984933586),
    name: 'Order',
    lastPropertyId: const obx_int.IdUid(7, 5719654511768375327),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8699183788851150282),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5010974492691083326),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3620983411732774766),
        name: 'totalAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5949424323690466824),
        name: 'customerId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8979272719527159501),
        name: 'pointsDelta',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7156356341069876081),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5719654511768375327),
        name: 'change',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1556823222891669075),
    name: 'Payment',
    lastPropertyId: const obx_int.IdUid(7, 1554447266613836857),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8664765915035793998),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7447122205749094462),
        name: 'orderId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 3381284353465803675),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5118637263179448851),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8093720518792403686),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8266630484826862053),
        name: 'methodValue',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1554447266613836857),
        name: 'value',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3928695168152462655),
    name: 'Product',
    lastPropertyId: const obx_int.IdUid(10, 9114141404640587778),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 712957492051500271),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 169156332966932451),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 506665631065279893),
        name: 'sku',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 7477663559896923451),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2199266134628594556),
        name: 'costPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 553431400252367335),
        name: 'salePrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6963349192326841419),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 492813275328730732),
        name: 'lowStockThreshold',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4972613303466048288),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3777265988992841748),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9114141404640587778),
        name: 'barcode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 755447607913665119),
    name: 'ProductBundle',
    lastPropertyId: const obx_int.IdUid(7, 6041153982624769768),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8040178166579613686),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5516992657247427629),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5394163487617214169),
        name: 'sku',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3173645816511167218),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 769586978561176688),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3004730022788702589),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6041153982624769768),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 8960357286126455536),
    name: 'ProductPrice',
    lastPropertyId: const obx_int.IdUid(7, 8196254604587282818),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3721334943696170200),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8882961972319715156),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8474995820643144454),
        name: 'storeId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4815853823610440097),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6953579305901720453),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6457229254087237519),
        name: 'validFrom',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8196254604587282818),
        name: 'validTo',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 4160568236184038516),
    name: 'ProductVariant',
    lastPropertyId: const obx_int.IdUid(9, 5704067055398917537),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1490116841357625283),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1536380005303908650),
        name: 'productId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(8, 2456266276138971225),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9003897549667772488),
        name: 'size',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8169473870311987615),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 406364419300370154),
        name: 'sku',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7848157240978095058),
        name: 'priceOverride',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8285670603010645715),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1728307465873355036),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5704067055398917537),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 1524308728038848094),
    name: 'Promotion',
    lastPropertyId: const obx_int.IdUid(9, 3711706257151908526),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6070053981611999733),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9208338812955167297),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 802417673979083518),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2255712237911823622),
        name: 'couponCode',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 6950328815289295310),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1243601122512220706),
        name: 'startAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3003510237892493909),
        name: 'endAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5379965124152368446),
        name: 'typeValue',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3711706257151908526),
        name: 'value',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 3265264959812195879),
    name: 'PurchaseOrder',
    lastPropertyId: const obx_int.IdUid(5, 4681598648861208045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7326378311508196838),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4574868150137166816),
        name: 'supplierId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(11, 529978939489516597),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8111406787949416437),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 921091273007799927),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4681598648861208045),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 6525069510032630285),
    name: 'Return',
    lastPropertyId: const obx_int.IdUid(8, 6787607481924054287),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4155886129623658776),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8691405479789759935),
        name: 'originalOrderId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7060228282144123074),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5491367048766129554),
        name: 'reason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7462972182287062470),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1758014498152972521),
        name: 'refundAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6567388609581195563),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6787607481924054287),
        name: 'customerId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 382108294515243333),
    name: 'StockAdjustment',
    lastPropertyId: const obx_int.IdUid(8, 6608960886877198749),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6105880656907297425),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7785844075627090453),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6351651679565405933),
        name: 'delta',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6123261918247963172),
        name: 'reason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2991451146201286036),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 984675749158998054),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2382397413665244864),
        name: 'batchNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6608960886877198749),
        name: 'expiryDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(14, 5132636966630793370),
    name: 'StockTransfer',
    lastPropertyId: const obx_int.IdUid(9, 1274055259032252356),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2920655699135583147),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4841025538047843762),
        name: 'fromStoreId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5164935773098485883),
        name: 'toStoreId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1883114793672434669),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8487227852139670367),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5623113292497692721),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7076965026171001891),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6690804353881943122),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1274055259032252356),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(15, 2354153997345506615),
    name: 'Store',
    lastPropertyId: const obx_int.IdUid(7, 6542228709510125332),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1759175786795938669),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7807557137715927673),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5702114139461352434),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 817827417832633038),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 242644920984149710),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5590065982190054877),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6542228709510125332),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(16, 8451655320088429338),
    name: 'Supplier',
    lastPropertyId: const obx_int.IdUid(7, 7978825957586630284),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7341155523653625865),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3858499319277469399),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 623559352065205733),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8134632766167012932),
        name: 'contactName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7070028414480552452),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8667957010976772598),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8870897686009140768),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7978825957586630284),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(17, 8719826114199624688),
    name: 'Customer',
    lastPropertyId: const obx_int.IdUid(6, 6222418345854308982),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4772293271083024492),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3733358829721652687),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 7661652707915618969),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8862049731596553159),
        name: 'phone',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(14, 6734691238513518003),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1854225994448980699),
        name: 'email',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(15, 5765196063137516024),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6336439270295329621),
        name: 'tier',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6222418345854308982),
        name: 'points',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(17, 8719826114199624688),
    lastIndexId: const obx_int.IdUid(15, 5765196063137516024),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7231150911437350149,
      336953188989827442,
      2010449398320011109,
      8682535331652953424,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppUser: obx_int.EntityDefinition<AppUser>(
      model: _entities[0],
      toOneRelations: (AppUser object) => [],
      toManyRelations: (AppUser object) => {},
      getId: (AppUser object) => object.id,
      setId: (AppUser object, int id) {
        object.id = id;
      },
      objectToFB: (AppUser object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        final passwordOffset = fbb.writeString(object.password);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usernameOffset);
        fbb.addOffset(2, passwordOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt8(5, object.roleValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AppUser()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..username = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..password = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..roleValue = const fb.Int8Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          );

        return object;
      },
    ),
    AuditLog: obx_int.EntityDefinition<AuditLog>(
      model: _entities[1],
      toOneRelations: (AuditLog object) => [],
      toManyRelations: (AuditLog object) => {},
      getId: (AuditLog object) => object.id,
      setId: (AuditLog object, int id) {
        object.id = id;
      },
      objectToFB: (AuditLog object, fb.Builder fbb) {
        final actionOffset = fbb.writeString(object.action);
        final detailsOffset = object.details == null
            ? null
            : fbb.writeString(object.details!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.userId);
        fbb.addOffset(2, actionOffset);
        fbb.addOffset(3, detailsOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AuditLog()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..userId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            6,
          )
          ..action = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..details = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          );

        return object;
      },
    ),
    GoodsReceipt: obx_int.EntityDefinition<GoodsReceipt>(
      model: _entities[2],
      toOneRelations: (GoodsReceipt object) => [],
      toManyRelations: (GoodsReceipt object) => {},
      getId: (GoodsReceipt object) => object.id,
      setId: (GoodsReceipt object, int id) {
        object.id = id;
      },
      objectToFB: (GoodsReceipt object, fb.Builder fbb) {
        final itemsJsonOffset = fbb.writeString(object.itemsJson);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.supplierId);
        fbb.addInt64(2, object.purchaseOrderId);
        fbb.addInt64(3, object.receivedAt.millisecondsSinceEpoch);
        fbb.addOffset(4, itemsJsonOffset);
        fbb.addOffset(5, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = GoodsReceipt()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..supplierId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..purchaseOrderId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            8,
          )
          ..receivedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..itemsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14);

        return object;
      },
    ),
    Order: obx_int.EntityDefinition<Order>(
      model: _entities[3],
      toOneRelations: (Order object) => [],
      toManyRelations: (Order object) => {},
      getId: (Order object) => object.id,
      setId: (Order object, int id) {
        object.id = id;
      },
      objectToFB: (Order object, fb.Builder fbb) {
        final itemsJsonOffset = fbb.writeString(object.itemsJson);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.createdAt.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.totalAmount);
        fbb.addInt64(3, object.customerId);
        fbb.addInt64(4, object.pointsDelta);
        fbb.addOffset(5, itemsJsonOffset);
        fbb.addFloat64(6, object.change);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Order()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
          )
          ..totalAmount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..customerId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            10,
          )
          ..pointsDelta = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..itemsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..change = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          );

        return object;
      },
    ),
    Payment: obx_int.EntityDefinition<Payment>(
      model: _entities[4],
      toOneRelations: (Payment object) => [],
      toManyRelations: (Payment object) => {},
      getId: (Payment object) => object.id,
      setId: (Payment object, int id) {
        object.id = id;
      },
      objectToFB: (Payment object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.orderId);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt8(5, object.methodValue);
        fbb.addFloat64(6, object.value);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Payment()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..orderId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..methodValue = const fb.Int8Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..value = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          );

        return object;
      },
    ),
    Product: obx_int.EntityDefinition<Product>(
      model: _entities[5],
      toOneRelations: (Product object) => [],
      toManyRelations: (Product object) => {},
      getId: (Product object) => object.id,
      setId: (Product object, int id) {
        object.id = id;
      },
      objectToFB: (Product object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final skuOffset = fbb.writeString(object.sku);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final barcodeOffset = object.barcode == null
            ? null
            : fbb.writeString(object.barcode!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, skuOffset);
        fbb.addFloat64(3, object.costPrice);
        fbb.addFloat64(4, object.salePrice);
        fbb.addInt64(5, object.stock);
        fbb.addInt64(6, object.lowStockThreshold);
        fbb.addOffset(7, categoryOffset);
        fbb.addOffset(8, descriptionOffset);
        fbb.addOffset(9, barcodeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Product()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..sku = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..costPrice = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..salePrice = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..stock = const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
          ..lowStockThreshold = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..category = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 18)
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 20)
          ..barcode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22);

        return object;
      },
    ),
    ProductBundle: obx_int.EntityDefinition<ProductBundle>(
      model: _entities[6],
      toOneRelations: (ProductBundle object) => [],
      toManyRelations: (ProductBundle object) => {},
      getId: (ProductBundle object) => object.id,
      setId: (ProductBundle object, int id) {
        object.id = id;
      },
      objectToFB: (ProductBundle object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final skuOffset = object.sku == null
            ? null
            : fbb.writeString(object.sku!);
        final itemsJsonOffset = fbb.writeString(object.itemsJson);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, skuOffset);
        fbb.addFloat64(3, object.price);
        fbb.addOffset(4, itemsJsonOffset);
        fbb.addBool(5, object.isActive);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ProductBundle()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..sku = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..price = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..itemsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          );

        return object;
      },
    ),
    ProductPrice: obx_int.EntityDefinition<ProductPrice>(
      model: _entities[7],
      toOneRelations: (ProductPrice object) => [],
      toManyRelations: (ProductPrice object) => {},
      getId: (ProductPrice object) => object.id,
      setId: (ProductPrice object, int id) {
        object.id = id;
      },
      objectToFB: (ProductPrice object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addInt64(2, object.storeId);
        fbb.addFloat64(3, object.price);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.validFrom?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.validTo?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final validFromValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final validToValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = ProductPrice()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..productId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..storeId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..price = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..validFrom = validFromValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(validFromValue)
          ..validTo = validToValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(validToValue);

        return object;
      },
    ),
    ProductVariant: obx_int.EntityDefinition<ProductVariant>(
      model: _entities[8],
      toOneRelations: (ProductVariant object) => [],
      toManyRelations: (ProductVariant object) => {},
      getId: (ProductVariant object) => object.id,
      setId: (ProductVariant object, int id) {
        object.id = id;
      },
      objectToFB: (ProductVariant object, fb.Builder fbb) {
        final sizeOffset = object.size == null
            ? null
            : fbb.writeString(object.size!);
        final colorOffset = object.color == null
            ? null
            : fbb.writeString(object.color!);
        final skuOffset = object.sku == null
            ? null
            : fbb.writeString(object.sku!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addOffset(2, sizeOffset);
        fbb.addOffset(3, colorOffset);
        fbb.addOffset(4, skuOffset);
        fbb.addFloat64(5, object.priceOverride);
        fbb.addInt64(6, object.stock);
        fbb.addBool(7, object.isActive);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ProductVariant()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..productId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..size = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..sku = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..priceOverride = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..stock = const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          );

        return object;
      },
    ),
    Promotion: obx_int.EntityDefinition<Promotion>(
      model: _entities[9],
      toOneRelations: (Promotion object) => [],
      toManyRelations: (Promotion object) => {},
      getId: (Promotion object) => object.id,
      setId: (Promotion object, int id) {
        object.id = id;
      },
      objectToFB: (Promotion object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final couponCodeOffset = object.couponCode == null
            ? null
            : fbb.writeString(object.couponCode!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, couponCodeOffset);
        fbb.addInt64(5, object.startAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endAt?.millisecondsSinceEpoch);
        fbb.addInt8(7, object.typeValue);
        fbb.addFloat64(8, object.value);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final endAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = Promotion()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..couponCode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..startAt = startAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(startAtValue)
          ..endAt = endAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endAtValue)
          ..typeValue = const fb.Int8Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..value = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          );

        return object;
      },
    ),
    PurchaseOrder: obx_int.EntityDefinition<PurchaseOrder>(
      model: _entities[10],
      toOneRelations: (PurchaseOrder object) => [],
      toManyRelations: (PurchaseOrder object) => {},
      getId: (PurchaseOrder object) => object.id,
      setId: (PurchaseOrder object, int id) {
        object.id = id;
      },
      objectToFB: (PurchaseOrder object, fb.Builder fbb) {
        final statusOffset = fbb.writeString(object.status);
        final itemsJsonOffset = fbb.writeString(object.itemsJson);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.supplierId);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(3, statusOffset);
        fbb.addOffset(4, itemsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PurchaseOrder()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..supplierId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..status = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..itemsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '');

        return object;
      },
    ),
    Return: obx_int.EntityDefinition<Return>(
      model: _entities[11],
      toOneRelations: (Return object) => [],
      toManyRelations: (Return object) => {},
      getId: (Return object) => object.id,
      setId: (Return object, int id) {
        object.id = id;
      },
      objectToFB: (Return object, fb.Builder fbb) {
        final reasonOffset = fbb.writeString(object.reason);
        final notesOffset = fbb.writeString(object.notes);
        final itemsJsonOffset = fbb.writeString(object.itemsJson);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.originalOrderId);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(3, reasonOffset);
        fbb.addOffset(4, notesOffset);
        fbb.addFloat64(5, object.refundAmount);
        fbb.addOffset(6, itemsJsonOffset);
        fbb.addInt64(7, object.customerId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Return()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..originalOrderId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..reason = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..refundAmount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..itemsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..customerId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            18,
          );

        return object;
      },
    ),
    StockAdjustment: obx_int.EntityDefinition<StockAdjustment>(
      model: _entities[12],
      toOneRelations: (StockAdjustment object) => [],
      toManyRelations: (StockAdjustment object) => {},
      getId: (StockAdjustment object) => object.id,
      setId: (StockAdjustment object, int id) {
        object.id = id;
      },
      objectToFB: (StockAdjustment object, fb.Builder fbb) {
        final reasonOffset = fbb.writeString(object.reason);
        final notesOffset = fbb.writeString(object.notes);
        final batchNumberOffset = object.batchNumber == null
            ? null
            : fbb.writeString(object.batchNumber!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addInt64(2, object.delta);
        fbb.addOffset(3, reasonOffset);
        fbb.addOffset(4, notesOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(6, batchNumberOffset);
        fbb.addInt64(7, object.expiryDate?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final expiryDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = StockAdjustment()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..productId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..delta = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..reason = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..batchNumber = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..expiryDate = expiryDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(expiryDateValue);

        return object;
      },
    ),
    StockTransfer: obx_int.EntityDefinition<StockTransfer>(
      model: _entities[13],
      toOneRelations: (StockTransfer object) => [],
      toManyRelations: (StockTransfer object) => {},
      getId: (StockTransfer object) => object.id,
      setId: (StockTransfer object, int id) {
        object.id = id;
      },
      objectToFB: (StockTransfer object, fb.Builder fbb) {
        final statusOffset = fbb.writeString(object.status);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.fromStoreId);
        fbb.addInt64(2, object.toStoreId);
        fbb.addInt64(3, object.productId);
        fbb.addInt64(4, object.quantity);
        fbb.addOffset(5, statusOffset);
        fbb.addOffset(6, notesOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.completedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final completedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = StockTransfer()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..fromStoreId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..toStoreId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..productId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..quantity = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..status = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..completedAt = completedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(completedAtValue);

        return object;
      },
    ),
    Store: obx_int.EntityDefinition<Store>(
      model: _entities[14],
      toOneRelations: (Store object) => [],
      toManyRelations: (Store object) => {},
      getId: (Store object) => object.id,
      setId: (Store object, int id) {
        object.id = id;
      },
      objectToFB: (Store object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final addressOffset = fbb.writeString(object.address);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addOffset(3, phoneOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addBool(5, object.isActive);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Store()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..address = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..phone = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..email = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          );

        return object;
      },
    ),
    Supplier: obx_int.EntityDefinition<Supplier>(
      model: _entities[15],
      toOneRelations: (Supplier object) => [],
      toManyRelations: (Supplier object) => {},
      getId: (Supplier object) => object.id,
      setId: (Supplier object, int id) {
        object.id = id;
      },
      objectToFB: (Supplier object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final contactNameOffset = object.contactName == null
            ? null
            : fbb.writeString(object.contactName!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, contactNameOffset);
        fbb.addOffset(3, phoneOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, addressOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Supplier()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..contactName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..phone = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..email = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..address = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          );

        return object;
      },
    ),
    Customer: obx_int.EntityDefinition<Customer>(
      model: _entities[16],
      toOneRelations: (Customer object) => [],
      toManyRelations: (Customer object) => {},
      getId: (Customer object) => object.id,
      setId: (Customer object, int id) {
        object.id = id;
      },
      objectToFB: (Customer object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final tierOffset = object.tier == null
            ? null
            : fbb.writeString(object.tier!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, phoneOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addOffset(4, tierOffset);
        fbb.addInt64(5, object.points);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Customer()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..phone = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..email = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..tier = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..points = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppUser] entity fields to define ObjectBox queries.
class AppUser_ {
  /// See [AppUser.id].
  static final id = obx.QueryIntegerProperty<AppUser>(
    _entities[0].properties[0],
  );

  /// See [AppUser.username].
  static final username = obx.QueryStringProperty<AppUser>(
    _entities[0].properties[1],
  );

  /// See [AppUser.password].
  static final password = obx.QueryStringProperty<AppUser>(
    _entities[0].properties[2],
  );

  /// See [AppUser.createdAt].
  static final createdAt = obx.QueryDateProperty<AppUser>(
    _entities[0].properties[3],
  );

  /// See [AppUser.roleValue].
  static final roleValue = obx.QueryIntegerProperty<AppUser>(
    _entities[0].properties[4],
  );
}

/// [AuditLog] entity fields to define ObjectBox queries.
class AuditLog_ {
  /// See [AuditLog.id].
  static final id = obx.QueryIntegerProperty<AuditLog>(
    _entities[1].properties[0],
  );

  /// See [AuditLog.userId].
  static final userId = obx.QueryIntegerProperty<AuditLog>(
    _entities[1].properties[1],
  );

  /// See [AuditLog.action].
  static final action = obx.QueryStringProperty<AuditLog>(
    _entities[1].properties[2],
  );

  /// See [AuditLog.details].
  static final details = obx.QueryStringProperty<AuditLog>(
    _entities[1].properties[3],
  );

  /// See [AuditLog.createdAt].
  static final createdAt = obx.QueryDateProperty<AuditLog>(
    _entities[1].properties[4],
  );
}

/// [GoodsReceipt] entity fields to define ObjectBox queries.
class GoodsReceipt_ {
  /// See [GoodsReceipt.id].
  static final id = obx.QueryIntegerProperty<GoodsReceipt>(
    _entities[2].properties[0],
  );

  /// See [GoodsReceipt.supplierId].
  static final supplierId = obx.QueryIntegerProperty<GoodsReceipt>(
    _entities[2].properties[1],
  );

  /// See [GoodsReceipt.purchaseOrderId].
  static final purchaseOrderId = obx.QueryIntegerProperty<GoodsReceipt>(
    _entities[2].properties[2],
  );

  /// See [GoodsReceipt.receivedAt].
  static final receivedAt = obx.QueryDateProperty<GoodsReceipt>(
    _entities[2].properties[3],
  );

  /// See [GoodsReceipt.itemsJson].
  static final itemsJson = obx.QueryStringProperty<GoodsReceipt>(
    _entities[2].properties[4],
  );

  /// See [GoodsReceipt.notes].
  static final notes = obx.QueryStringProperty<GoodsReceipt>(
    _entities[2].properties[5],
  );
}

/// [Order] entity fields to define ObjectBox queries.
class Order_ {
  /// See [Order.id].
  static final id = obx.QueryIntegerProperty<Order>(_entities[3].properties[0]);

  /// See [Order.createdAt].
  static final createdAt = obx.QueryDateProperty<Order>(
    _entities[3].properties[1],
  );

  /// See [Order.totalAmount].
  static final totalAmount = obx.QueryDoubleProperty<Order>(
    _entities[3].properties[2],
  );

  /// See [Order.customerId].
  static final customerId = obx.QueryIntegerProperty<Order>(
    _entities[3].properties[3],
  );

  /// See [Order.pointsDelta].
  static final pointsDelta = obx.QueryIntegerProperty<Order>(
    _entities[3].properties[4],
  );

  /// See [Order.itemsJson].
  static final itemsJson = obx.QueryStringProperty<Order>(
    _entities[3].properties[5],
  );

  /// See [Order.change].
  static final change = obx.QueryDoubleProperty<Order>(
    _entities[3].properties[6],
  );
}

/// [Payment] entity fields to define ObjectBox queries.
class Payment_ {
  /// See [Payment.id].
  static final id = obx.QueryIntegerProperty<Payment>(
    _entities[4].properties[0],
  );

  /// See [Payment.orderId].
  static final orderId = obx.QueryIntegerProperty<Payment>(
    _entities[4].properties[1],
  );

  /// See [Payment.amount].
  static final amount = obx.QueryDoubleProperty<Payment>(
    _entities[4].properties[2],
  );

  /// See [Payment.createdAt].
  static final createdAt = obx.QueryDateProperty<Payment>(
    _entities[4].properties[3],
  );

  /// See [Payment.methodValue].
  static final methodValue = obx.QueryIntegerProperty<Payment>(
    _entities[4].properties[4],
  );

  /// See [Payment.value].
  static final value = obx.QueryDoubleProperty<Payment>(
    _entities[4].properties[5],
  );
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// See [Product.id].
  static final id = obx.QueryIntegerProperty<Product>(
    _entities[5].properties[0],
  );

  /// See [Product.name].
  static final name = obx.QueryStringProperty<Product>(
    _entities[5].properties[1],
  );

  /// See [Product.sku].
  static final sku = obx.QueryStringProperty<Product>(
    _entities[5].properties[2],
  );

  /// See [Product.costPrice].
  static final costPrice = obx.QueryDoubleProperty<Product>(
    _entities[5].properties[3],
  );

  /// See [Product.salePrice].
  static final salePrice = obx.QueryDoubleProperty<Product>(
    _entities[5].properties[4],
  );

  /// See [Product.stock].
  static final stock = obx.QueryIntegerProperty<Product>(
    _entities[5].properties[5],
  );

  /// See [Product.lowStockThreshold].
  static final lowStockThreshold = obx.QueryIntegerProperty<Product>(
    _entities[5].properties[6],
  );

  /// See [Product.category].
  static final category = obx.QueryStringProperty<Product>(
    _entities[5].properties[7],
  );

  /// See [Product.description].
  static final description = obx.QueryStringProperty<Product>(
    _entities[5].properties[8],
  );

  /// See [Product.barcode].
  static final barcode = obx.QueryStringProperty<Product>(
    _entities[5].properties[9],
  );
}

/// [ProductBundle] entity fields to define ObjectBox queries.
class ProductBundle_ {
  /// See [ProductBundle.id].
  static final id = obx.QueryIntegerProperty<ProductBundle>(
    _entities[6].properties[0],
  );

  /// See [ProductBundle.name].
  static final name = obx.QueryStringProperty<ProductBundle>(
    _entities[6].properties[1],
  );

  /// See [ProductBundle.sku].
  static final sku = obx.QueryStringProperty<ProductBundle>(
    _entities[6].properties[2],
  );

  /// See [ProductBundle.price].
  static final price = obx.QueryDoubleProperty<ProductBundle>(
    _entities[6].properties[3],
  );

  /// See [ProductBundle.itemsJson].
  static final itemsJson = obx.QueryStringProperty<ProductBundle>(
    _entities[6].properties[4],
  );

  /// See [ProductBundle.isActive].
  static final isActive = obx.QueryBooleanProperty<ProductBundle>(
    _entities[6].properties[5],
  );

  /// See [ProductBundle.createdAt].
  static final createdAt = obx.QueryDateProperty<ProductBundle>(
    _entities[6].properties[6],
  );
}

/// [ProductPrice] entity fields to define ObjectBox queries.
class ProductPrice_ {
  /// See [ProductPrice.id].
  static final id = obx.QueryIntegerProperty<ProductPrice>(
    _entities[7].properties[0],
  );

  /// See [ProductPrice.productId].
  static final productId = obx.QueryIntegerProperty<ProductPrice>(
    _entities[7].properties[1],
  );

  /// See [ProductPrice.storeId].
  static final storeId = obx.QueryIntegerProperty<ProductPrice>(
    _entities[7].properties[2],
  );

  /// See [ProductPrice.price].
  static final price = obx.QueryDoubleProperty<ProductPrice>(
    _entities[7].properties[3],
  );

  /// See [ProductPrice.createdAt].
  static final createdAt = obx.QueryDateProperty<ProductPrice>(
    _entities[7].properties[4],
  );

  /// See [ProductPrice.validFrom].
  static final validFrom = obx.QueryDateProperty<ProductPrice>(
    _entities[7].properties[5],
  );

  /// See [ProductPrice.validTo].
  static final validTo = obx.QueryDateProperty<ProductPrice>(
    _entities[7].properties[6],
  );
}

/// [ProductVariant] entity fields to define ObjectBox queries.
class ProductVariant_ {
  /// See [ProductVariant.id].
  static final id = obx.QueryIntegerProperty<ProductVariant>(
    _entities[8].properties[0],
  );

  /// See [ProductVariant.productId].
  static final productId = obx.QueryIntegerProperty<ProductVariant>(
    _entities[8].properties[1],
  );

  /// See [ProductVariant.size].
  static final size = obx.QueryStringProperty<ProductVariant>(
    _entities[8].properties[2],
  );

  /// See [ProductVariant.color].
  static final color = obx.QueryStringProperty<ProductVariant>(
    _entities[8].properties[3],
  );

  /// See [ProductVariant.sku].
  static final sku = obx.QueryStringProperty<ProductVariant>(
    _entities[8].properties[4],
  );

  /// See [ProductVariant.priceOverride].
  static final priceOverride = obx.QueryDoubleProperty<ProductVariant>(
    _entities[8].properties[5],
  );

  /// See [ProductVariant.stock].
  static final stock = obx.QueryIntegerProperty<ProductVariant>(
    _entities[8].properties[6],
  );

  /// See [ProductVariant.isActive].
  static final isActive = obx.QueryBooleanProperty<ProductVariant>(
    _entities[8].properties[7],
  );

  /// See [ProductVariant.createdAt].
  static final createdAt = obx.QueryDateProperty<ProductVariant>(
    _entities[8].properties[8],
  );
}

/// [Promotion] entity fields to define ObjectBox queries.
class Promotion_ {
  /// See [Promotion.id].
  static final id = obx.QueryIntegerProperty<Promotion>(
    _entities[9].properties[0],
  );

  /// See [Promotion.name].
  static final name = obx.QueryStringProperty<Promotion>(
    _entities[9].properties[1],
  );

  /// See [Promotion.couponCode].
  static final couponCode = obx.QueryStringProperty<Promotion>(
    _entities[9].properties[2],
  );

  /// See [Promotion.startAt].
  static final startAt = obx.QueryDateProperty<Promotion>(
    _entities[9].properties[3],
  );

  /// See [Promotion.endAt].
  static final endAt = obx.QueryDateProperty<Promotion>(
    _entities[9].properties[4],
  );

  /// See [Promotion.typeValue].
  static final typeValue = obx.QueryIntegerProperty<Promotion>(
    _entities[9].properties[5],
  );

  /// See [Promotion.value].
  static final value = obx.QueryDoubleProperty<Promotion>(
    _entities[9].properties[6],
  );
}

/// [PurchaseOrder] entity fields to define ObjectBox queries.
class PurchaseOrder_ {
  /// See [PurchaseOrder.id].
  static final id = obx.QueryIntegerProperty<PurchaseOrder>(
    _entities[10].properties[0],
  );

  /// See [PurchaseOrder.supplierId].
  static final supplierId = obx.QueryIntegerProperty<PurchaseOrder>(
    _entities[10].properties[1],
  );

  /// See [PurchaseOrder.createdAt].
  static final createdAt = obx.QueryDateProperty<PurchaseOrder>(
    _entities[10].properties[2],
  );

  /// See [PurchaseOrder.status].
  static final status = obx.QueryStringProperty<PurchaseOrder>(
    _entities[10].properties[3],
  );

  /// See [PurchaseOrder.itemsJson].
  static final itemsJson = obx.QueryStringProperty<PurchaseOrder>(
    _entities[10].properties[4],
  );
}

/// [Return] entity fields to define ObjectBox queries.
class Return_ {
  /// See [Return.id].
  static final id = obx.QueryIntegerProperty<Return>(
    _entities[11].properties[0],
  );

  /// See [Return.originalOrderId].
  static final originalOrderId = obx.QueryIntegerProperty<Return>(
    _entities[11].properties[1],
  );

  /// See [Return.createdAt].
  static final createdAt = obx.QueryDateProperty<Return>(
    _entities[11].properties[2],
  );

  /// See [Return.reason].
  static final reason = obx.QueryStringProperty<Return>(
    _entities[11].properties[3],
  );

  /// See [Return.notes].
  static final notes = obx.QueryStringProperty<Return>(
    _entities[11].properties[4],
  );

  /// See [Return.refundAmount].
  static final refundAmount = obx.QueryDoubleProperty<Return>(
    _entities[11].properties[5],
  );

  /// See [Return.itemsJson].
  static final itemsJson = obx.QueryStringProperty<Return>(
    _entities[11].properties[6],
  );

  /// See [Return.customerId].
  static final customerId = obx.QueryIntegerProperty<Return>(
    _entities[11].properties[7],
  );
}

/// [StockAdjustment] entity fields to define ObjectBox queries.
class StockAdjustment_ {
  /// See [StockAdjustment.id].
  static final id = obx.QueryIntegerProperty<StockAdjustment>(
    _entities[12].properties[0],
  );

  /// See [StockAdjustment.productId].
  static final productId = obx.QueryIntegerProperty<StockAdjustment>(
    _entities[12].properties[1],
  );

  /// See [StockAdjustment.delta].
  static final delta = obx.QueryIntegerProperty<StockAdjustment>(
    _entities[12].properties[2],
  );

  /// See [StockAdjustment.reason].
  static final reason = obx.QueryStringProperty<StockAdjustment>(
    _entities[12].properties[3],
  );

  /// See [StockAdjustment.notes].
  static final notes = obx.QueryStringProperty<StockAdjustment>(
    _entities[12].properties[4],
  );

  /// See [StockAdjustment.createdAt].
  static final createdAt = obx.QueryDateProperty<StockAdjustment>(
    _entities[12].properties[5],
  );

  /// See [StockAdjustment.batchNumber].
  static final batchNumber = obx.QueryStringProperty<StockAdjustment>(
    _entities[12].properties[6],
  );

  /// See [StockAdjustment.expiryDate].
  static final expiryDate = obx.QueryDateProperty<StockAdjustment>(
    _entities[12].properties[7],
  );
}

/// [StockTransfer] entity fields to define ObjectBox queries.
class StockTransfer_ {
  /// See [StockTransfer.id].
  static final id = obx.QueryIntegerProperty<StockTransfer>(
    _entities[13].properties[0],
  );

  /// See [StockTransfer.fromStoreId].
  static final fromStoreId = obx.QueryIntegerProperty<StockTransfer>(
    _entities[13].properties[1],
  );

  /// See [StockTransfer.toStoreId].
  static final toStoreId = obx.QueryIntegerProperty<StockTransfer>(
    _entities[13].properties[2],
  );

  /// See [StockTransfer.productId].
  static final productId = obx.QueryIntegerProperty<StockTransfer>(
    _entities[13].properties[3],
  );

  /// See [StockTransfer.quantity].
  static final quantity = obx.QueryIntegerProperty<StockTransfer>(
    _entities[13].properties[4],
  );

  /// See [StockTransfer.status].
  static final status = obx.QueryStringProperty<StockTransfer>(
    _entities[13].properties[5],
  );

  /// See [StockTransfer.notes].
  static final notes = obx.QueryStringProperty<StockTransfer>(
    _entities[13].properties[6],
  );

  /// See [StockTransfer.createdAt].
  static final createdAt = obx.QueryDateProperty<StockTransfer>(
    _entities[13].properties[7],
  );

  /// See [StockTransfer.completedAt].
  static final completedAt = obx.QueryDateProperty<StockTransfer>(
    _entities[13].properties[8],
  );
}

/// [Store] entity fields to define ObjectBox queries.
class Store_ {
  /// See [Store.id].
  static final id = obx.QueryIntegerProperty<Store>(
    _entities[14].properties[0],
  );

  /// See [Store.name].
  static final name = obx.QueryStringProperty<Store>(
    _entities[14].properties[1],
  );

  /// See [Store.address].
  static final address = obx.QueryStringProperty<Store>(
    _entities[14].properties[2],
  );

  /// See [Store.phone].
  static final phone = obx.QueryStringProperty<Store>(
    _entities[14].properties[3],
  );

  /// See [Store.email].
  static final email = obx.QueryStringProperty<Store>(
    _entities[14].properties[4],
  );

  /// See [Store.isActive].
  static final isActive = obx.QueryBooleanProperty<Store>(
    _entities[14].properties[5],
  );

  /// See [Store.createdAt].
  static final createdAt = obx.QueryDateProperty<Store>(
    _entities[14].properties[6],
  );
}

/// [Supplier] entity fields to define ObjectBox queries.
class Supplier_ {
  /// See [Supplier.id].
  static final id = obx.QueryIntegerProperty<Supplier>(
    _entities[15].properties[0],
  );

  /// See [Supplier.name].
  static final name = obx.QueryStringProperty<Supplier>(
    _entities[15].properties[1],
  );

  /// See [Supplier.contactName].
  static final contactName = obx.QueryStringProperty<Supplier>(
    _entities[15].properties[2],
  );

  /// See [Supplier.phone].
  static final phone = obx.QueryStringProperty<Supplier>(
    _entities[15].properties[3],
  );

  /// See [Supplier.email].
  static final email = obx.QueryStringProperty<Supplier>(
    _entities[15].properties[4],
  );

  /// See [Supplier.address].
  static final address = obx.QueryStringProperty<Supplier>(
    _entities[15].properties[5],
  );

  /// See [Supplier.createdAt].
  static final createdAt = obx.QueryDateProperty<Supplier>(
    _entities[15].properties[6],
  );
}

/// [Customer] entity fields to define ObjectBox queries.
class Customer_ {
  /// See [Customer.id].
  static final id = obx.QueryIntegerProperty<Customer>(
    _entities[16].properties[0],
  );

  /// See [Customer.name].
  static final name = obx.QueryStringProperty<Customer>(
    _entities[16].properties[1],
  );

  /// See [Customer.phone].
  static final phone = obx.QueryStringProperty<Customer>(
    _entities[16].properties[2],
  );

  /// See [Customer.email].
  static final email = obx.QueryStringProperty<Customer>(
    _entities[16].properties[3],
  );

  /// See [Customer.tier].
  static final tier = obx.QueryStringProperty<Customer>(
    _entities[16].properties[4],
  );

  /// See [Customer.points].
  static final points = obx.QueryIntegerProperty<Customer>(
    _entities[16].properties[5],
  );
}
